FROM python:3.12-slim

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app
COPY main.py /app/

ENV PYTHONPATH=/app

EXPOSE 5000

CMD ["python3", "main.py"]